### ISSUE TITLE
[PE-D][Tester F] set-diet-goals command not clear in the UG

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2113-T17-1/tp#162]
Based on the syntax, it shows that the last 4 parameters are optional based on the Notes about Command Format.

![image.png](https://raw.githubusercontent.com/sRanay/ped/main/files/0cf5da4e-a030-43d0-86f1-e72d36a18b39.png)

This works: `set-diet-goal WEEKLY calories/500 fats/600`

This doesnt work: `set-diet-goal WEEKLY` doesnt work.

Maybe can make the documentation clearer.

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: sRanay/ped#3

**Comment by yicheng-toh** [comment]
![image](https://github.com/AY2324S1-CS2113-T17-1/tp/assets/75836313/64c3e751-6770-4c78-812b-f371b28af199)
It is mentioned that at least one is supported!

**Comment by yicheng-toh** [comment]
Please read the userguide properly!!!! HOW DARE YOU HAVE THE GUTS TO PUT A FREAKING MEDIUM PRIORITY WHEN IT IS A YOU PROBLEM!!!!
Mentioned in pull request #231
