### ISSUE TITLE
[PE-D][Tester E] add-activity duration is included, but still gives error message saying there is an issue

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2113-T17-1/tp#163]
No details provided by bug reporter.

![image.png](https://raw.githubusercontent.com/marklin2234/ped/main/files/313b0bfc-d673-45ed-97ac-c7178ba732f0.png)

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: marklin2234/ped#1

**Comment by yicheng-toh** [comment]
I think it is because of the space. Maybe mention in the UG or edit the code?
