### ISSUE TITLE
[PE-D][Tester B] Time not displaying seconds

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2113-T17-1/tp#164]
![image.png](https://raw.githubusercontent.com/Xuan127/ped/main/files/25121360-cbff-4dc6-9c0c-85614c496dcb.png)

Time is not displaying seconds, I think its fine, but then the input should not require seconds to save the user time

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: Xuan127/ped#2

**Comment by AlWo223** [comment]
Duplicate of #178 (no data loss, just condensed view)
