### ISSUE TITLE
[PE-D][Tester C] `duration` cannot end in `:59:59`

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2113-T17-1/tp#195]
The program does not accept input if the duration ends in `:59:59`.

![image.png](https://raw.githubusercontent.com/antrikshdhand/ped/main/files/7cee4dab-79b9-46df-ad1a-a0ab8a6aee32.png)

When inputting `23:59:58` though, the program accepts it.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: antrikshdhand/ped#4

**Comment by AlWo223** [comment]
Can not reproduce, maybe system specific error?
