### ISSUE TITLE
[PE-D][Tester B] edit-diet-goal dont have example command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2113-T17-1/tp#203]
![image.png](https://raw.githubusercontent.com/Xuan127/ped/main/files/c8f372ef-aef8-4cfe-8370-7cf3752e4153.png)

edit-diet-goal dont have example command

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: Xuan127/ped#11

**Comment by yicheng-toh** [comment]
Repeated

**Comment by yicheng-toh** [comment]
It is below the sleep user guide. You clearly did not read properly!

**Comment by yicheng-toh** [comment]
The example is found at the bottom of the UG. 
Mentioned in pull request #231
