### ISSUE TITLE
[PE-D][Tester C] Save functionality does not work

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2113-T17-1/tp#209]
**Note from the teaching team:** This bug was reported during the _Part II (Evaluating Documents)_ stage of the PE. **You may reject this bug if it is not related to the quality of documentation.**<hr>
No activities are saved upon exiting the application.

![image.png](https://raw.githubusercontent.com/antrikshdhand/ped/main/files/317ffc18-5b65-489c-8772-83386186a740.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: antrikshdhand/ped#6

**Comment by yicheng-toh** [comment]
Similar to issue #227
