### ISSUE TITLE
Application crashes after entering a date that is very long ago for add-sleep

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2113-T17-1/tp#213]
**Note from the teaching team:** This bug was reported during the _Part II (Evaluating Documents)_ stage of the PE. **You may reject this bug if it is not related to the quality of documentation.**<hr>
The command I used is: ` add-sleep start/1001-01-20 00:00 end/2023-01-20 08:00`

The application crashed as soon as I entered that command

![image.png](https://raw.githubusercontent.com/sRanay/ped/main/files/c17021e7-3a00-488f-9de8-a0cccac056cc.png)

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: sRanay/ped#10

**Comment by yicheng-toh** [comment]
Similar to #217

**Comment by DaDevChia** [comment]
Implement check for dates that are too long ago and throw error
