### ISSUE TITLE
[PE-D][Tester B] Nothing is being saved to file except diet_goal

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2113-T17-1/tp#218]
**Note from the teaching team:** This bug was reported during the _Part II (Evaluating Documents)_ stage of the PE. **You may reject this bug if it is not related to the quality of documentation.**<hr>
![image.png](https://raw.githubusercontent.com/Xuan127/ped/main/files/0fdf660a-8a9d-416b-ae95-611d186856cc.png)

added activities, activity-goals, diets, sleeps and none gets saved to file

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: Xuan127/ped#16

**Comment by yicheng-toh** [comment]
Same as issue #227
