### ISSUE TITLE
[PE-D][Tester F] Unable to add diet goals despite having 0 diet goal in the application

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2113-T17-1/tp#222]
**Note from the teaching team:** This bug was reported during the _Part II (Evaluating Documents)_ stage of the PE. **You may reject this bug if it is not related to the quality of documentation.**<hr>
As shown in the screenshot below, despite having 0 diet-goal created and checked using the command `list-diet-goal`, I am unable to create a diet-goal.

![image.png](https://raw.githubusercontent.com/sRanay/ped/main/files/b1307a1a-fd6b-4d4e-bf83-ed7f6ddd80b2.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: sRanay/ped#11

**Comment by yicheng-toh** [comment]
Hi, thanks for your feedback. However, the command to list diet goal is list-diet-goal.
The list diet command is for the meals that you have logged.

**Comment by yicheng-toh** [comment]
This is a YOU problem. You did not read the user guide properly. GO AWAY!
