### ISSUE TITLE
[PE-D][Tester A] save function not working

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2113-T17-1/tp#227]
**Note from the teaching team:** This bug was reported during the _Part II (Evaluating Documents)_ stage of the PE. **You may reject this bug if it is not related to the quality of documentation.**<hr>
![image.png](https://raw.githubusercontent.com/KenCheung18/ped/main/files/21cf77e4-3066-4b7b-88f0-71adc8a7ee17.png)

![image.png](https://raw.githubusercontent.com/KenCheung18/ped/main/files/5a913872-51df-497b-bc2a-bd57721feb2a.png)

I used both the auto save and save function but it still not saving anything

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: KenCheung18/ped#14

**Comment by yicheng-toh** [comment]
To include parsing and unparsing of data.
