### ISSUE TITLE
Repetition handling for editing diets

### ISSUE THREAD

**Issue by yicheng-toh** [AY2324S1-CS2113-T17-1/tp#287]
Affected command:
edit-diet 1 calories/500 fat/20 protein/20 carb/50 fat/10 datetime/2021-09-01 06:00
![image](https://github.com/AY2324S1-CS2113-T17-1/tp/assets/75836313/ce6e3794-cb64-478e-bc89-652b4fc41af4)

**Comment by nihalzp** [comment]
Only the first argument and value will be accepted; it is possible to do the extra check and not allow duplicate marker; but I think it does not affect usability.

**Comment by yicheng-toh** [comment]
did you mention it in the ug?

**Comment by nihalzp** [comment]
I have added extra checks to disallow duplicate arguments and throw an error.
