### ISSUE TITLE
edit diet hhmmss accepted even though ss not indicated

### ISSUE THREAD

**Issue by yicheng-toh** [AY2324S1-CS2113-T17-1/tp#291]
![image](https://github.com/AY2324S1-CS2113-T17-1/tp/assets/75836313/8eb91b6f-04e1-442e-8c6c-514e7a44a5cb)

**Comment by nihalzp** [comment]
This problem seemed universal to all datetime parsing. I have made changes to throw error when hhmmss is given instead of hhmm.
