### ISSUE TITLE
Find-sleep returns only first matching entry

### ISSUE THREAD

**Issue by AlWo223** [AY2324S1-CS2113-T17-1/tp#299]
<img width="1125" alt="image" src="https://github.com/AY2324S1-CS2113-T17-1/tp/assets/62311026/7f8b3001-75a4-4c0e-9f2a-b2ab483ab53c">

Scenario: You go to bad after a club visit (lets say 7:00 am in the morning) and go to bed on the same day as usual (lets say 11:00 pm) --> Both will be same day but reasonable entries which should both be printed

**Comment by DaDevChia** [comment]
Find-sleep returns all matching entries on the date itself, just that it considers all sleeps with start time before 6am to be before.
