### ISSUE TITLE
Activity saving format not standardized with sleep/diet

### ISSUE THREAD

**Issue by DaDevChia** [AY2324S1-CS2113-T17-1/tp#312]
![Screenshot 2023-11-13 at 3 10 35 AM](https://github.com/AY2324S1-CS2113-T17-1/tp/assets/88506363/96ce69ae-33fb-4d61-a821-0fc4f15c3f39)
![Screenshot 2023-11-13 at 3 10 39 AM](https://github.com/AY2324S1-CS2113-T17-1/tp/assets/88506363/06907f13-450e-4855-abb8-341b434b26e1)
Currently activity file is saved with the [activity] prefix, but not sleep and diet. We should standardize this

**Comment by yicheng-toh** [comment]
so 
diet => [Diet]
activity => [Activity]
sleep => [Sleep]?
Then their corresponding goals too?

**Comment by AlWo223** [comment]
This is required for activity as the different activity types Swim, Run, etc. need to be parsed differently. Feel free to follow this format for standardisation reasons but I guess it does not really have any benefit for your implementations.

**Comment by nihalzp** [comment]
Having the extra [prefix] is going to make implementation complicated. For example, without the extra [prefix], the implementation is as simple as clean as:
<img width="492" alt="Screenshot 2023-11-13 at 11 40 45 AM" src="https://github.com/AY2324S1-CS2113-T17-1/tp/assets/81457724/947e964e-e3a6-47d0-8116-a2ff49b2889a">
