### ISSUE TITLE
Delete Activity Goal does not exist but is still referenced in help messages

### ISSUE THREAD

**Issue by DaDevChia** [AY2324S1-CS2113-T17-1/tp#313]
![Screenshot 2023-11-13 at 3 19 30 AM](https://github.com/AY2324S1-CS2113-T17-1/tp/assets/88506363/519c251d-ef05-4e57-9059-0bfd04911d99)

**Comment by AlWo223** [comment]
Works for me, can you try to reproduce the commands you used?

**Comment by nihalzp** [comment]
![image](https://github.com/AY2324S1-CS2113-T17-1/tp/assets/81457724/ebecdd94-75a8-4179-b8b7-5b34d3b0d582)
Seems like `delete-activity-goal` is working as intended.
