### ISSUE TITLE
Sleep edit limited usefulness due to non-optimal parameters

### ISSUE THREAD

**Issue by AlWo223** [AY2324S1-CS2113-T17-1/tp#315]
It seems equally convenient or even faster to delete and add sleep instead of editing sleep. Making the command handle optional parameters will increase the feature value of editing.

Even though it requires only 2 params, it will most likely be flagged as a feature flaw due to above-mentioned reasons.

It might be straightforward to implement for only 2 params. But if not in scope and the risk of new bugs is too high feel free to close issue.

**Comment by DaDevChia** [comment]
Not in scope
