### ISSUE TITLE
Diet Goal Handle Big Integer Input

### ISSUE THREAD

**Issue by nihalzp** [AY2324S1-CS2113-T17-1/tp#318]
![image](https://github.com/AY2324S1-CS2113-T17-1/tp/assets/81457724/8f16f9c4-9309-4d21-aa0d-ae3c505cc821)

**Comment by nihalzp** [comment]
![image](https://github.com/AY2324S1-CS2113-T17-1/tp/assets/81457724/7c76e01f-ed24-4259-8d92-944fac1917a2)
Also for the `delete-diet-goal index` as well.

**Comment by yicheng-toh** [comment]
It is indicated in the UG that it only takes on an integer.
