### ISSUE TITLE
Standardisation Issue: "Fats" used in Diet Goal and "Fat" in Diet

### ISSUE THREAD

**Issue by nihalzp** [AY2324S1-CS2113-T17-1/tp#319]
Initially I choose `fat` because `protein`, `carb` were in singular form as well. Should we use `fat` everywhere to be consistent?

**Comment by yicheng-toh** [comment]
fats is a noun and fat is an adjective. so I  believe the use of fats makes more sense.

**Comment by nihalzp** [comment]
Good point. However, as far as I know, fat can be noun as well.

![image](https://github.com/AY2324S1-CS2113-T17-1/tp/assets/81457724/1a00f26c-9967-4ccd-856d-f4ddf993a21a)

I am on the side of `fat` since we have used singular nouns for `protein` and `carb`.
