### ISSUE TITLE
Wrong command format for delete-activity-goal in UG

### ISSUE THREAD

**Issue by AlWo223** [AY2324S1-CS2113-T17-1/tp#328]
<img width="627" alt="Screenshot 2023-11-13 at 10 43 21" src="https://github.com/AY2324S1-CS2113-T17-1/tp/assets/62311026/883630cd-dda6-47ae-ad34-39164da264dd">

The syntax for deleting activity goals in UG is wrong, it should be **type/TYPE instead of target/TARGET**

**Comment by nihalzp** [comment]
Thank you very much for pointing it out. I am fixing it in the next PR.
