### ISSUE TITLE
Update manual tests for DG

### ISSUE THREAD

**Issue by yicheng-toh** [AY2324S1-CS2113-T17-1/tp#331]
Update manual tests for DG .
Maybe look at address book or TA's project for inspiration

Is the DG due on the same day as the code?

**Comment by skylee03** [comment]
The deadline for DG is 2023-11-14 13:00.

**Comment by AlWo223** [comment]
Is this mandatory and what is the expectation (how many test scenarios?)

**Comment by skylee03** [comment]
> Is this mandatory and what is the expectation (how many test scenarios?)

https://nus-cs2113-ay2324s1.github.io/website/admin/tp-deliverables.html#deliverable-developer-guide-dg
![image](https://github.com/AY2324S1-CS2113-T17-1/tp/assets/24489025/246e414f-82e9-40ed-a853-5a9a1c8b3971)
