### ISSUE TITLE
Implement New Goal Class: Activity, Sleep, and Diet Goals

### ISSUE THREAD

**Issue by DaDevChia** [AY2324S1-CS2113-T17-1/tp#73]
#### Description:

Incorporate a new class for goals across `activity`, `sleep`, and `diet` to enable more structured tracking and retrieval of set goals.

#### Command Specifications:

1.  **Setting Goals**:
    
    *   **Weekly Goals**:
        
        ```
        goal-set-[activity|sleep|diet] <value> -weekof <date>
        ```
        
        For example:
   
        
        ```
        goal-set-sleep 7H -weekof 22-10-2023
        ```
        
    *   **Monthly Goals** (For future implementation):
        
        
        ```
        goal-set-[activity|sleep|diet] <value> -monthof <date>
        ```
        
        If `-weekof` or `-monthof` is specified, the time reference is set accordingly. Otherwise, the system will use the current time to determine the current week/month.
        
        **Storage example**: Storing a sleep goal of 7H from 15-10-2023 to 22-10-2023.
        
2.  **Listing Goals**:
    
    *   **Weekly Goals**:
        
        
        ```
        goal-list-[activity|sleep|diet] -weekof <date>
        ```
        
        For example:
       
        
        ```
        goal-list-sleep -weekof 20-10-2023
        ```
        
    *   **Monthly Goals** (For future implementation):
        
        
        ```
        goal-list-[activity|sleep|diet] -monthof <date>
        ```
        
        If `-weekof` or `-monthof` is specified, the time reference is set. Otherwise, the current time is used to determine the current week/month.
        
    
    **Example Response**: "You have not met your target sleep goal for this week."
    

#### Expected Outcome:

User should be able to seamlessly set and retrieve their weekly (and in the future, monthly) goals for activity, sleep, and diet.

---

**Comment by DaDevChia** [comment]
Weekly goal tracker where 

goal-set-sleep 7H WEEKOF 22-10-2023
if we specify WEEKOF -> time reference is set
otherwise we use currenttime to determine week
store: sleep goal of 7H from 15-10-2023 to 22-10-2023

goal-list-sleep WEEKOF 20-10-2023 (refer to same week as above)
if we specify WEEKOF -> time reference is set
otherwise we use currenttime to determine week
tell me >
You have not met your target sleep goal for this week

**Comment by yicheng-toh** [comment]
Can I confirm:
1. We will have a abstract goal class for all sleep/activity/diet goals to inherit from
2. The command to set goals will be changed
3.  The -weekof variable is compulsory. and it would be indicated by the '-' which is not found in other commands.
4. The date input is strictly dd-mm-yyyy.
